/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import AccesoADatos.ContratoData;
import Entidades.Contrato;
import Entidades.Persona;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Veronica Porqueras
 */
public class AdmContratos extends javax.swing.JDialog {

    /**
     * Creates new form AdmContratos
     */
    private ContratoData controlContrato = new ContratoData();
    private Persona inquilino = null;
    private Persona garante = null;

    public AdmContratos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        colorBG();
        cargarInmueble();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bCrear = new javax.swing.JLabel();
        jpInquilino = new javax.swing.JPanel();
        jtInquilino = new javax.swing.JTextField();
        bBuscarInquilino1 = new javax.swing.JLabel();
        TXTinquilino1 = new javax.swing.JLabel();
        NombreInquilino = new javax.swing.JLabel();
        ApellidoInquilino = new javax.swing.JLabel();
        DniInquilino = new javax.swing.JLabel();
        CuilInquilino = new javax.swing.JLabel();
        DireccionInquilino = new javax.swing.JLabel();
        TelefonoInquilino = new javax.swing.JLabel();
        eMailInquilino = new javax.swing.JLabel();
        jpGarante = new javax.swing.JPanel();
        jtGarante = new javax.swing.JTextField();
        NombreGarante = new javax.swing.JLabel();
        ApellidoGarante = new javax.swing.JLabel();
        DniGarante = new javax.swing.JLabel();
        CuilGarante = new javax.swing.JLabel();
        DireccionGarante = new javax.swing.JLabel();
        TelefonoGarante = new javax.swing.JLabel();
        eMailGarante = new javax.swing.JLabel();
        TXTGarante = new javax.swing.JLabel();
        bBuscargarante = new javax.swing.JLabel();
        jpInmueble = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlDireccion = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jlCodigo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jdcFirma = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdcInicio = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jdcFinalizacion = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDetallesContrato = new javax.swing.JTextArea();
        jtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bCrear.setBackground(new java.awt.Color(51, 51, 255));
        bCrear.setFont(new java.awt.Font("Univers-Black", 0, 18)); // NOI18N
        bCrear.setForeground(new java.awt.Color(255, 255, 255));
        bCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bCrear.setText("CREAR");
        bCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCrearMouseClicked(evt);
            }
        });
        jPanel1.add(bCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, 30));

        jtInquilino.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        jtInquilino.setForeground(new java.awt.Color(51, 0, 51));
        jtInquilino.setText("ingrese DNI del inquilino");
        jtInquilino.setBorder(null);
        jtInquilino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtInquilinoMouseClicked(evt);
            }
        });
        jtInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtInquilinoActionPerformed(evt);
            }
        });
        jtInquilino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtInquilinoKeyTyped(evt);
            }
        });

        bBuscarInquilino1.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        bBuscarInquilino1.setForeground(new java.awt.Color(255, 255, 255));
        bBuscarInquilino1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregarPerson.png"))); // NOI18N
        bBuscarInquilino1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBuscarInquilino1MouseClicked(evt);
            }
        });

        TXTinquilino1.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        TXTinquilino1.setForeground(new java.awt.Color(255, 255, 255));
        TXTinquilino1.setText("Inquilino");

        NombreInquilino.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        NombreInquilino.setForeground(new java.awt.Color(255, 255, 255));
        NombreInquilino.setText("Nombre");

        ApellidoInquilino.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        ApellidoInquilino.setForeground(new java.awt.Color(255, 255, 255));
        ApellidoInquilino.setText("Apellido");

        DniInquilino.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        DniInquilino.setForeground(new java.awt.Color(255, 255, 255));
        DniInquilino.setText("DNI");

        CuilInquilino.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        CuilInquilino.setForeground(new java.awt.Color(255, 255, 255));
        CuilInquilino.setText("CUIL/CUIT");

        DireccionInquilino.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        DireccionInquilino.setForeground(new java.awt.Color(255, 255, 255));
        DireccionInquilino.setText("Direccion");

        TelefonoInquilino.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        TelefonoInquilino.setForeground(new java.awt.Color(255, 255, 255));
        TelefonoInquilino.setText("telefono");

        eMailInquilino.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        eMailInquilino.setForeground(new java.awt.Color(255, 255, 255));
        eMailInquilino.setText("eMail");

        javax.swing.GroupLayout jpInquilinoLayout = new javax.swing.GroupLayout(jpInquilino);
        jpInquilino.setLayout(jpInquilinoLayout);
        jpInquilinoLayout.setHorizontalGroup(
            jpInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInquilinoLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(TXTinquilino1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bBuscarInquilino1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInquilinoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInquilinoLayout.createSequentialGroup()
                        .addComponent(NombreInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ApellidoInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInquilinoLayout.createSequentialGroup()
                        .addComponent(DireccionInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(CuilInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInquilinoLayout.createSequentialGroup()
                        .addComponent(DniInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(TelefonoInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eMailInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jpInquilinoLayout.setVerticalGroup(
            jpInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTinquilino1)
                        .addComponent(jtInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bBuscarInquilino1))
                .addGap(18, 18, 18)
                .addGroup(jpInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreInquilino)
                    .addComponent(ApellidoInquilino))
                .addGap(14, 14, 14)
                .addGroup(jpInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DireccionInquilino)
                    .addComponent(CuilInquilino))
                .addGap(14, 14, 14)
                .addGroup(jpInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DniInquilino)
                    .addComponent(TelefonoInquilino))
                .addGap(14, 14, 14)
                .addComponent(eMailInquilino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jpInquilino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 170));

        jpGarante.setForeground(new java.awt.Color(255, 255, 255));

        jtGarante.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        jtGarante.setForeground(new java.awt.Color(51, 0, 51));
        jtGarante.setText("ingrese DNI del Garante");
        jtGarante.setBorder(null);
        jtGarante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtGaranteMouseClicked(evt);
            }
        });
        jtGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtGaranteActionPerformed(evt);
            }
        });
        jtGarante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtGaranteKeyTyped(evt);
            }
        });

        NombreGarante.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        NombreGarante.setForeground(new java.awt.Color(255, 255, 255));
        NombreGarante.setText("Nombre");

        ApellidoGarante.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        ApellidoGarante.setForeground(new java.awt.Color(255, 255, 255));
        ApellidoGarante.setText("Apellido");

        DniGarante.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        DniGarante.setForeground(new java.awt.Color(255, 255, 255));
        DniGarante.setText("DNI");

        CuilGarante.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        CuilGarante.setForeground(new java.awt.Color(255, 255, 255));
        CuilGarante.setText("CUIL/CUIT");

        DireccionGarante.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        DireccionGarante.setForeground(new java.awt.Color(255, 255, 255));
        DireccionGarante.setText("Direccion");

        TelefonoGarante.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        TelefonoGarante.setForeground(new java.awt.Color(255, 255, 255));
        TelefonoGarante.setText("telefono");

        eMailGarante.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        eMailGarante.setForeground(new java.awt.Color(255, 255, 255));
        eMailGarante.setText("eMail");

        TXTGarante.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        TXTGarante.setForeground(new java.awt.Color(255, 255, 255));
        TXTGarante.setText("Garante");

        bBuscargarante.setFont(new java.awt.Font("Univers LT Std 55", 0, 14)); // NOI18N
        bBuscargarante.setForeground(new java.awt.Color(255, 255, 255));
        bBuscargarante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregarPerson.png"))); // NOI18N
        bBuscargarante.setText("Buscar");
        bBuscargarante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBuscargaranteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpGaranteLayout = new javax.swing.GroupLayout(jpGarante);
        jpGarante.setLayout(jpGaranteLayout);
        jpGaranteLayout.setHorizontalGroup(
            jpGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGaranteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGaranteLayout.createSequentialGroup()
                        .addComponent(TXTGarante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bBuscargarante))
                    .addGroup(jpGaranteLayout.createSequentialGroup()
                        .addComponent(NombreGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApellidoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpGaranteLayout.createSequentialGroup()
                        .addComponent(DniGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CuilGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eMailGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpGaranteLayout.createSequentialGroup()
                        .addComponent(DireccionGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TelefonoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpGaranteLayout.setVerticalGroup(
            jpGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGaranteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTGarante)
                        .addComponent(jtGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bBuscargarante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreGarante)
                    .addComponent(ApellidoGarante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DniGarante)
                    .addComponent(CuilGarante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionGarante)
                    .addComponent(TelefonoGarante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eMailGarante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jpGarante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 410, 160));

        jpInmueble.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Univers LT Std 45 Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inmueble");

        jlDireccion.setFont(new java.awt.Font("Univers LT Std 45 Light", 0, 14)); // NOI18N
        jlDireccion.setForeground(new java.awt.Color(255, 255, 255));
        jlDireccion.setText("Direccion");

        jLabelCodigo.setFont(new java.awt.Font("Univers LT Std 45 Light", 0, 14)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigo.setText("Codigo:");

        jlCodigo.setFont(new java.awt.Font("Univers LT Std 45 Light", 0, 14)); // NOI18N
        jlCodigo.setText("           ");

        jLabel2.setFont(new java.awt.Font("Univers LT Std 45 Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FIRMA");

        jLabel3.setFont(new java.awt.Font("Univers LT Std 45 Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INICIO");

        jLabel4.setFont(new java.awt.Font("Univers LT Std 45 Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FINALIZACION");

        jtaDetallesContrato.setColumns(20);
        jtaDetallesContrato.setRows(5);
        jScrollPane1.setViewportView(jtaDetallesContrato);

        jtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jtPrecio.setText("ingrese el valor ");
        jtPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPrecioMouseClicked(evt);
            }
        });
        jtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPrecioKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Univers LT Std 45 Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio:");

        javax.swing.GroupLayout jpInmuebleLayout = new javax.swing.GroupLayout(jpInmueble);
        jpInmueble.setLayout(jpInmuebleLayout);
        jpInmuebleLayout.setHorizontalGroup(
            jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInmuebleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInmuebleLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInmuebleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(jpInmuebleLayout.createSequentialGroup()
                        .addGroup(jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpInmuebleLayout.createSequentialGroup()
                                .addComponent(jLabelCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jlDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jpInmuebleLayout.createSequentialGroup()
                        .addGroup(jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdcFirma, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInmuebleLayout.createSequentialGroup()
                                .addGroup(jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdcInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdcFinalizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jtPrecio))
                        .addContainerGap())))
        );
        jpInmuebleLayout.setVerticalGroup(
            jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInmuebleLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jlCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpInmuebleLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jdcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpInmuebleLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(jdcFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpInmuebleLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(jdcFinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(jpInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jpInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 370, 380));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BG_Contrato.png"))); // NOI18N
        BG.setMaximumSize(new java.awt.Dimension(810, 400));
        BG.setMinimumSize(new java.awt.Dimension(810, 400));
        BG.setPreferredSize(new java.awt.Dimension(810, 400));
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtGaranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtGaranteActionPerformed

    private void jtInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtInquilinoActionPerformed

    private void bBuscarInquilino1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBuscarInquilino1MouseClicked
        String dato = (String) jtInquilino.getText();
        int dni = Integer.parseInt(dato);
        inquilino = MVendedor.controlPer.encontrarPersona(dni);
        if (inquilino != null) {
            NombreInquilino.setText(inquilino.getNombre());
            ApellidoInquilino.setText(inquilino.getApellido());
            DireccionInquilino.setText(inquilino.getDomicilio());
            DniInquilino.setText(inquilino.getDni() + "");
            CuilInquilino.setText(inquilino.getCuil() + "");
            TelefonoInquilino.setText(inquilino.getTelefono() + "");
            eMailInquilino.setText(inquilino.getEmail());

        } else {

            Object[] opciones = {"Si", "No", "Cancelar"};       //Crea un Vector con los textos a mostrar
            int opcion = JOptionPane.showOptionDialog(null,
                    "El DNI no se encuentra en la Base de Datos ¿Desea agregar la persona?",
                    "Confirmacion",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    null, opciones, opciones[1]);

            if (opcion == JOptionPane.YES_OPTION) {
                AdmPersona carga = new AdmPersona(null, rootPaneCheckingEnabled);
                carga.setLocationRelativeTo(null);
                carga.setVisible(true);
            } else if (opcion == JOptionPane.CANCEL_OPTION) {
                jtInquilino.setText("");
            } else {
            }

        }

    }//GEN-LAST:event_bBuscarInquilino1MouseClicked

    private void bBuscargaranteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBuscargaranteMouseClicked
        String dato = jtGarante.getText();
        int dni = Integer.parseInt(dato);
        garante = MVendedor.controlPer.encontrarPersona(dni);
        if (garante != null) {
            NombreGarante.setText(garante.getNombre());
            ApellidoGarante.setText(garante.getApellido());
            DireccionGarante.setText(garante.getDomicilio());
            DniGarante.setText(garante.getDni() + "");
            CuilGarante.setText(garante.getCuil() + "");
            TelefonoGarante.setText(garante.getTelefono() + "");
            eMailGarante.setText(garante.getEmail());

        } else {

            Object[] opciones = {"Si", "No", "Cancelar"};       //Crea un Vector con los textos a mostrar
            int opcion = JOptionPane.showOptionDialog(null,
                    "El DNI no se encuentra en la Base de Datos ¿Desea agregar la persona?",
                    "Confirmacion",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    null, opciones, opciones[1]);

            if (opcion == JOptionPane.YES_OPTION) {
                AdmPersona carga = new AdmPersona(null, rootPaneCheckingEnabled);
                carga.setLocationRelativeTo(null);
                carga.setVisible(true);
            } else if (opcion == JOptionPane.CANCEL_OPTION) {
                jtInquilino.setText("");
            } else {
            }
        }
    }//GEN-LAST:event_bBuscargaranteMouseClicked

    private void jtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecioKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_ENTER) {
            evt.consume(); // Consumir el evento si no es una letra o espacio
            JOptionPane.showMessageDialog(null, "Solo se pueden poner Numeros");

        }
    }//GEN-LAST:event_jtPrecioKeyTyped

    private void jtGaranteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtGaranteKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_ENTER) {
            evt.consume(); // Consumir el evento si no es una letra o espacio
            JOptionPane.showMessageDialog(null, "Solo se pueden poner Numeros");

        }
    }//GEN-LAST:event_jtGaranteKeyTyped

    private void jtInquilinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtInquilinoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_ENTER) {
            evt.consume(); // Consumir el evento si no es una letra o espacio
            JOptionPane.showMessageDialog(null, "Solo se pueden poner Numeros");

        }
    }//GEN-LAST:event_jtInquilinoKeyTyped

    private void jtInquilinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtInquilinoMouseClicked
        jtInquilino.setText("");
    }//GEN-LAST:event_jtInquilinoMouseClicked

    private void jtGaranteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtGaranteMouseClicked
        jtGarante.setText("");
    }//GEN-LAST:event_jtGaranteMouseClicked

    private void bCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCrearMouseClicked
         guardar();
    }//GEN-LAST:event_bCrearMouseClicked

    private void jtPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPrecioMouseClicked
       jtPrecio.setText("");
    }//GEN-LAST:event_jtPrecioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdmContratos dialog = new AdmContratos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoGarante;
    private javax.swing.JLabel ApellidoInquilino;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel CuilGarante;
    private javax.swing.JLabel CuilInquilino;
    private javax.swing.JLabel DireccionGarante;
    private javax.swing.JLabel DireccionInquilino;
    private javax.swing.JLabel DniGarante;
    private javax.swing.JLabel DniInquilino;
    private javax.swing.JLabel NombreGarante;
    private javax.swing.JLabel NombreInquilino;
    private javax.swing.JLabel TXTGarante;
    private javax.swing.JLabel TXTinquilino1;
    private javax.swing.JLabel TelefonoGarante;
    private javax.swing.JLabel TelefonoInquilino;
    private javax.swing.JLabel bBuscarInquilino1;
    private javax.swing.JLabel bBuscargarante;
    private javax.swing.JLabel bCrear;
    private javax.swing.JLabel eMailGarante;
    private javax.swing.JLabel eMailInquilino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JDateChooser jdcFinalizacion;
    private com.toedter.calendar.JDateChooser jdcFirma;
    private com.toedter.calendar.JDateChooser jdcInicio;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JPanel jpGarante;
    private javax.swing.JPanel jpInmueble;
    private javax.swing.JPanel jpInquilino;
    private javax.swing.JTextField jtGarante;
    private javax.swing.JTextField jtInquilino;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextArea jtaDetallesContrato;
    // End of variables declaration//GEN-END:variables
    private void colorBG() {
        Color fondo = new Color(23, 36, 46, 240);
        jpInquilino.setBackground(fondo);
        jpGarante.setBackground(fondo);
        jpInmueble.setBackground(fondo);
    }
    private void cargarInmueble(){
    jlDireccion.setText(MVendedor.inmubleSeleccionado.getDireccion());
    jlCodigo.setText(MVendedor.inmubleSeleccionado.getId()+"");
    
    }

    private void guardar() {
        try {
            int idInmueble = MVendedor.inmubleSeleccionado.getId();
            int idInquilino = inquilino.getId();
            int idGarante = garante.getId();
            int idVendedor = MVendedor.vendedor.getId();
            int precio = Integer.parseInt(jtPrecio.getText());
            LocalDate fContrato = jdcFirma.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fInicio = jdcInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fFinaliza = jdcFinalizacion.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String descripcion = jtaDetallesContrato.getText();
            Contrato nuevo = new Contrato(idInmueble,
                    idInquilino, idGarante, idVendedor,
                    fContrato, fInicio, fFinaliza,
                    precio, "VIGENTE", descripcion);
            if (fContrato == null) {
                JOptionPane.showMessageDialog(null, "Ingrese la fecha de firma del contrato");
            }
            if (fInicio == null) {
                JOptionPane.showMessageDialog(null, "Ingrese la fecha de firma del contrato");
            }
            if (fFinaliza == null) {
                JOptionPane.showMessageDialog(null, "Ingrese la fecha de firma del contrato");
            }
            controlContrato.crearContrato(nuevo);
        } catch (NullPointerException np) {
            JOptionPane.showMessageDialog(null, "todos los datos son Necesarios");
        }

    }
}
