package GUI;

import AccesoADatos.PersonaData;
import Entidades.Persona;
import static GUI.MVendedor.controlPer;
import java.time.LocalDate;
import java.time.ZoneId;

import javax.swing.JOptionPane;

/**
 *
 * @author Veronica Porqueras
 */
public class AdmInmuebles extends javax.swing.JDialog {
    
    
    private Persona buscado;
    
    
    public AdmInmuebles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CargarCombo();
        setTitle("Administración de Inmuebles");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBAlta = new javax.swing.JButton();
        jLPropietario = new javax.swing.JLabel();
        jLSuperficie = new javax.swing.JLabel();
        jLAmbientes = new javax.swing.JLabel();
        jLBanios = new javax.swing.JLabel();
        jLGarage = new javax.swing.JLabel();
        jLDireccion = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jLZona = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTDireccion = new javax.swing.JTextField();
        jTSuperficie = new javax.swing.JTextField();
        jTZona = new javax.swing.JTextField();
        jTAmbientes = new javax.swing.JTextField();
        jTBanios = new javax.swing.JTextField();
        jTGarage = new javax.swing.JTextField();
        jTTipoInmueble = new javax.swing.JTextField();
        jTEstado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBBaja = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTNomYApe = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jCBuscar = new javax.swing.JComboBox<>();
        jTDniId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBAlta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBAlta.setText("Alta");
        jPanel1.add(jBAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jLPropietario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLPropietario.setText("Buscar por :");
        jPanel1.add(jLPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLSuperficie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLSuperficie.setText("Superficie :");
        jPanel1.add(jLSuperficie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLAmbientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLAmbientes.setText("Cantidad de ambientes :");
        jPanel1.add(jLAmbientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLBanios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBanios.setText("Cantidad de baños :");
        jPanel1.add(jLBanios, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLGarage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLGarage.setText("Garage :");
        jPanel1.add(jLGarage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLDireccion.setText("Dirección del Inmueble :");
        jPanel1.add(jLDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLEstado.setText("Estado :");
        jPanel1.add(jLEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLZona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLZona.setText("Zona :");
        jPanel1.add(jLZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        jLTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLTipo.setText("Tipo de Inmueble :");
        jPanel1.add(jLTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Condiciones del propietario para el contrato :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        jPanel1.add(jTDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 210, -1));
        jPanel1.add(jTSuperficie, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 40, -1));
        jPanel1.add(jTZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 40, -1));
        jPanel1.add(jTAmbientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 40, -1));
        jPanel1.add(jTBanios, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 40, -1));
        jPanel1.add(jTGarage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 40, -1));
        jPanel1.add(jTTipoInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 40, -1));
        jPanel1.add(jTEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 70, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 370, 70));

        jBBaja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBBaja.setText("Baja");
        jBBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBajaActionPerformed(evt);
            }
        });
        jPanel1.add(jBBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        jBSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, -1, -1));

        jBEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBEditar.setText("Editar");
        jPanel1.add(jBEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        jBBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LUPA.png"))); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 130, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel1.add(jTNomYApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));

        jBGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBGuardar.setText("Guardar");
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Apellido :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));
        jPanel1.add(jTApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 170, -1));

        jCBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jCBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));
        jPanel1.add(jTDniId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBajaActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        String seleccionado = (String) jCBuscar.getSelectedItem();
        if (seleccionado == "DNI Propietario") {
            int dni = Integer.parseInt(jTDniId.getText());
            buscado = controlPer.encontrarPersona(dni);
            
            if (buscado == null) {
                
                Object[] opciones = {"SI", "NO", "CANCELAR"};
                int opcion = JOptionPane.showOptionDialog(null,
                "El DNI ingresado no existe, desea agregarlo?",
                "Confirmacion",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.YES_NO_OPTION,
                null, opciones, opciones[2]);
                if (opcion == JOptionPane.YES_OPTION) {
                    
                    limpiarJt();
                    jBBuscar.setEnabled(false);
                    jBAlta.setEnabled(false);
                    jBBaja.setEnabled(false);
                    jBEditar.setEnabled(false);
                    AdmPersona.controlPer.agregarPersona(buscado);
                    
                } else {
                        
                                       
                }
            
            JOptionPane.showMessageDialog(null, "Debe ingresar un DNI");
        } else if (seleccionado == "ID Propietario"){
            
            int id = Integer.parseInt(seleccionado);
            buscado = controlPer.encontrarPersona(id);
            
            if (buscado == null) {
                
                Object[] opciones = {"SI", "NO", "CANCELAR"};
                int opcion = JOptionPane.showOptionDialog(null,
                "El ID ingresado no existe.",
                "Confirmacion",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.YES_NO_OPTION,
                null, opciones, opciones[2]);
                if (opcion == JOptionPane.YES_OPTION) {
                    
                    limpiarJt();
                    jBBuscar.setEnabled(false);
                    jBAlta.setEnabled(false);
                    jBBaja.setEnabled(false);
                    jBEditar.setEnabled(false);
                    AdmPersona.controlPer.agregarPersona(buscado);
                    
                } else {
                        
                                       
                }
                
                
            }
            int dni = Integer.parseInt(jTPropietario.getText());
            buscado = controlPer.encontrarPersona(dni);
            if (buscado == null) {
            
            }else{
                String nombre = buscado.getNombre();
                String apellido = buscado.getApellido();
                jTNomYApe.setText(nombre+" "+apellido);
                jTDireccion.setText(buscado.getDomicilio());
                
            }
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdmInmuebles dialog = new AdmInmuebles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlta;
    private javax.swing.JButton jBBaja;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCBuscar;
    private javax.swing.JLabel jLAmbientes;
    private javax.swing.JLabel jLBanios;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLGarage;
    private javax.swing.JLabel jLPropietario;
    private javax.swing.JLabel jLSuperficie;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLZona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTAmbientes;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTBanios;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTDniId;
    private javax.swing.JTextField jTEstado;
    private javax.swing.JTextField jTGarage;
    private javax.swing.JTextField jTNomYApe;
    private javax.swing.JTextField jTSuperficie;
    private javax.swing.JTextField jTTipoInmueble;
    private javax.swing.JTextField jTZona;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    
public void CargarCombo(){
    jCBuscar.addItem("DNI Propietario");
    jCBuscar.addItem("ID Propietario");
    
}    
    
public void limpiarJt() {
    
        jTSuperficie.setText("");
        jTAmbientes.setText("");
        jTBanios.setText("");
        jTDireccion.setText("");
        jTEstado.setText("");
        jTGarage.setText("");
        jTTipoInmueble.setText("");
        jTZona.setText("");
                
    }

}
