/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import AccesoADatos.UsuarioData;
import Entidades.Persona;
import Entidades.Usuario;
import static GUI.AdmPersona.controlPer;
import java.awt.Font;
import static GUI.MAdministrador.nombre;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class AdmUsuarios extends javax.swing.JDialog {

    private Persona buscada;
    private Usuario mostrado;
    private boolean editar;
    private final Font label = MVendedor.fuenteLabel;
    private final Font boton = MVendedor.fuenteBoton12;
    private final Font nombre = MVendedor.fuenteBoton18;
    private final Font title = MVendedor.fuenteNombre;

    public AdmUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initFont();
        limpiarCampos();
        bloquearCampos();
        jbGuardar.setText("GUARDAR");
        jbEditar.setEnabled(false);
        jbGuardar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jtfDni = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jchbEstado = new javax.swing.JCheckBox();
        jbEditar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jcbTipo = new javax.swing.JComboBox<>();
        jbSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jpContrasenia = new javax.swing.JPasswordField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(410, 440));
        setResizable(false);
        setSize(new java.awt.Dimension(410, 440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INGRESE EL DNI DE LA PERSONA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 105, -1, 30));

        jlNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 147, 320, 30));

        jtfDni.setBackground(new java.awt.Color(30, 62, 88));
        jtfDni.setForeground(new java.awt.Color(255, 255, 255));
        jtfDni.setBorder(null);
        jtfDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDniKeyTyped(evt);
            }
        });
        getContentPane().add(jtfDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 105, 190, 30));

        jbBuscar.setBackground(new java.awt.Color(30, 62, 88));
        jbBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jbBuscar.setText("Buscar");
        jbBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 332, 100, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 147, 60, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USUARIO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 192, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONTRASEÑA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 237, 90, 30));

        jchbEstado.setBackground(new java.awt.Color(30, 62, 88));
        jchbEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jchbEstado.setForeground(new java.awt.Color(255, 255, 255));
        jchbEstado.setText("EN ACTIVIDAD");
        getContentPane().add(jchbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 283, -1, 30));

        jbEditar.setBackground(new java.awt.Color(30, 62, 88));
        jbEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbEditar.setForeground(new java.awt.Color(255, 255, 255));
        jbEditar.setText("EDITAR");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 332, 100, 40));

        jbGuardar.setBackground(new java.awt.Color(30, 62, 88));
        jbGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbGuardar.setText("GUARDAR");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 332, 100, 40));

        jcbTipo.setBackground(new java.awt.Color(30, 62, 88));
        jcbTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbTipo.setForeground(new java.awt.Color(255, 255, 255));
        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "INSPECTOR", "VENDEDOR" }));
        getContentPane().add(jcbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 283, -1, 30));

        jbSalir.setBackground(new java.awt.Color(30, 62, 88));
        jbSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("SALIR");
        jbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSalirMouseClicked(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 332, 90, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("TIPO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 283, -1, 30));

        jtfUsuario.setBackground(new java.awt.Color(30, 62, 88));
        jtfUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jtfUsuario.setBorder(null);
        getContentPane().add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 192, 300, 30));

        jpContrasenia.setBackground(new java.awt.Color(30, 62, 88));
        jpContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        jpContrasenia.setText("jPasswordField1");
        jpContrasenia.setBorder(null);
        getContentPane().add(jpContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 237, 280, 30));

        Background.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BG_usuarios.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 420, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBuscarMouseClicked
        limpiarCampos();
        buscar();
        if (mostrado == null) {
            editar = false;
            jbEditar.setEnabled(false);
            jbGuardar.setEnabled(true);
            jbGuardar.setText("CREAR");
        } else {
            editar = true;
            jbEditar.setEnabled(true);
            jbGuardar.setText("GUARDAR");
            jbGuardar.setEnabled(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jbBuscarMouseClicked

    private void jtfDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            evt.consume();
            buscar();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDniKeyTyped

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        jbGuardar.setEnabled(true);
        jbEditar.setEnabled(false);
        desbloquearCampos();// TODO add your handling code here:
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSalirMouseClicked
        limpiarCampos();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalirMouseClicked

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        guardar();
        limpiarCampos();
    }//GEN-LAST:event_jbGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdmUsuarios dialog = new AdmUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JCheckBox jchbEstado;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JPasswordField jpContrasenia;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
   private void initFont() {

        jLabel2.setFont(label);
        jLabel3.setFont(label);
        jLabel5.setFont(label);
        jLabel6.setFont(label);
        jLabel7.setFont(label);
        jcbTipo.setFont(label);
        jchbEstado.setFont(label);
        jlNombre.setFont(label);
        jpContrasenia.setFont(label);
        jtfDni.setFont(label);
        jtfUsuario.setFont(label);
        jbBuscar.setFont(nombre);
        jbEditar.setFont(boton);
        jbGuardar.setFont(boton);
        jbSalir.setFont(boton);
    }

    private void bloquearCampos() {
        jlNombre.setEnabled(false);
        jtfUsuario.setEnabled(false);
        jpContrasenia.setEnabled(false);
        jcbTipo.setEnabled(false);
        jchbEstado.setEnabled(false);
    }

    private void desbloquearCampos() {
        jlNombre.setEnabled(true);
        jtfUsuario.setEnabled(true);
        jpContrasenia.setEnabled(true);
        jcbTipo.setEnabled(true);
        jchbEstado.setEnabled(true);
    }

    private void limpiarCampos() {
        jlNombre.setText("");
        jtfUsuario.setText("");
        jpContrasenia.setText("");
        jcbTipo.setSelectedItem("");
        jchbEstado.setEnabled(false);
    }

    private void buscar() {
        try {
            if (jtfDni.getText().isEmpty() || jtfDni.getText().equals(" ")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un DNI");
            } else {
                int dni = Integer.parseInt(jtfDni.getText());
                buscada = controlPer.encontrarPersona(dni);
                if (buscada == null) {
                    Object[] opciones = {"Si", "No"};       //Crea un Vector con los textos a mostrar
                    int opcion = JOptionPane.showOptionDialog(null,
                            "No existe una persona con el DNI ingresado ¿Desea agregarla?",
                            "Confirmacion",
                            JOptionPane.DEFAULT_OPTION,
                            JOptionPane.YES_NO_CANCEL_OPTION,
                            null, opciones, opciones[1]);

                    if (opcion == JOptionPane.YES_OPTION) {
                        AdmPersona carga = new AdmPersona(null, rootPaneCheckingEnabled);
                        carga.setLocationRelativeTo(null);
                        carga.setVisible(true);
                    } else if (opcion == JOptionPane.NO_OPTION) {
                        jtfDni.setText("");
                    }
                } else {
                    int idPersona = buscada.getId();

                    mostrado = MAdministrador.controlUsuario.buscarUsuarioxIdPersona(idPersona);
                    if (mostrado == null) {
                        jlNombre.setText(buscada.getNombre() + buscada.getApellido());
                        editar = false;
                        desbloquearCampos();
                    } else {
                        editar = true;
                        jlNombre.setText(buscada.getApellido() + ", " + buscada.getNombre());
                        jtfUsuario.setText(mostrado.getUsuario());
                        jpContrasenia.setText(mostrado.getContraseña());
                        String comboMostrado = mostrado.getTipo();
                        switch (comboMostrado) {
                            case "A":
                                jcbTipo.setSelectedItem("ADMINISTRADOR");
                                break;
                            case "I":
                                jcbTipo.setSelectedItem("INSPECTOR");
                                break;
                            case "V":
                                jcbTipo.setSelectedItem("VENDEDOR");
                                break;
                        }
                        jchbEstado.setSelected(mostrado.isEstado());
                    }

                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe ingresar sólo números");
        }
    }

    private void guardar() {
        if (jtfUsuario.getText().isEmpty() || jpContrasenia.getPassword() == null) {
            JOptionPane.showConfirmDialog(null, "Todos los campos son necesarios!");
        } else {
            int dni = Integer.parseInt(jtfDni.getText());
            String cbox = null;
            String password = String.valueOf(jpContrasenia.getPassword());
            buscada = controlPer.encontrarPersona(dni);
            int idUsuario = buscada.getId();
            String comboEditado = String.valueOf(jcbTipo.getSelectedItem());
            switch (comboEditado) {
                case "ADMINISTRADOR":
                    cbox = "A";
                    break;
                case "INSPECTOR":
                    cbox = "I";
                    break;
                case "VENDEDOR":
                    cbox = "V";
                    break;
            }

            if (editar) {
                Usuario editado = new Usuario(mostrado.getId(), idUsuario, jtfUsuario.getText(), password, cbox, jchbEstado.isSelected());
                MAdministrador.controlUsuario.actualizarUsuario(editado);
                mostrado = null;
            } else {
                if (validarUser(jtfUsuario.getText())) {
                    Usuario editado = new Usuario(idUsuario, jtfUsuario.getText(), password, cbox, jchbEstado.isSelected());
                    MAdministrador.controlUsuario.RegistrarUsuario(editado);
                }

            }

        }
    }

    public boolean validarUser(String nombre) {
        Usuario encontrado = MAdministrador.controlUsuario.buscarUsuario(nombre);
        if (encontrado != null) {
            JOptionPane.showMessageDialog(null, " Ya existe el usuario " + encontrado.getUsuario() + ", ingrese otro.");
            return false;
        }
        return true;
    }

}
