package GUI;

import AccesoADatos.UsuarioData;
import Entidades.Usuario;
import static GUI.MAdministrador.cargarFuentePersonalizada;
import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando Acevedo
 */
public class Logging extends javax.swing.JFrame {

    /**
     * Creates new form log
     */
    public static Font fuenteBoton18 = cargarFuentePersonalizada("src/Img/font/UniversBlack.ttf", 18);
    public static Font fuenteBoton14 = cargarFuentePersonalizada("src/Img/font/UniversBlack.ttf", 14);
    public static Font nombre = cargarFuentePersonalizada("src/Img/font/UniversBlack.ttf", 32);
    public static Font label = cargarFuentePersonalizada("src/Img/font/Univers-light-normal.ttf", 12);
    
    private UsuarioData usuarioData = new UsuarioData();
    private int xMouse, yMouse;
    public Logging() {
        initComponents();
        initFont();
        calendario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barra = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        diaSemana = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        mes = new javax.swing.JLabel();
        Calendario = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jpPass = new javax.swing.JPasswordField();
        jlSalir = new javax.swing.JLabel();
        jlIngresar = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barra.setOpaque(false);
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 20));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo100p.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        diaSemana.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        diaSemana.setForeground(new java.awt.Color(0, 0, 0));
        diaSemana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diaSemana.setText("lunes");
        jPanel1.add(diaSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 90, -1));

        dia.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        dia.setForeground(new java.awt.Color(204, 0, 0));
        dia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dia.setText("1");
        jPanel1.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 90, -1));

        mes.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        mes.setForeground(new java.awt.Color(51, 51, 51));
        mes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mes.setText("mes");
        jPanel1.add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, -1));

        Calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/calendar.png"))); // NOI18N
        jPanel1.add(Calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 130));

        jtUsuario.setBackground(new java.awt.Color(40, 62, 49));
        jtUsuario.setForeground(new java.awt.Color(178, 208, 158));
        jtUsuario.setText("Ingrese su nombre de Usuario y contraseña");
        jtUsuario.setBorder(null);
        jtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 280, 30));

        jpPass.setBackground(new java.awt.Color(40, 62, 49));
        jpPass.setForeground(new java.awt.Color(178, 208, 158));
        jpPass.setText("contraseña");
        jpPass.setBorder(null);
        jpPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpPassMouseClicked(evt);
            }
        });
        jpPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpPassKeyTyped(evt);
            }
        });
        jPanel1.add(jpPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 280, 30));

        jlSalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlSalir.setForeground(new java.awt.Color(178, 208, 158));
        jlSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalir.setText("SALIR");
        jlSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlSalirMouseExited(evt);
            }
        });
        jPanel1.add(jlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 90, 30));

        jlIngresar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlIngresar.setForeground(new java.awt.Color(178, 208, 158));
        jlIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIngresar.setText("INGRESAR");
        jlIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlIngresarMouseExited(evt);
            }
        });
        jPanel1.add(jlIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 90, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bg.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseEntered
        jlSalir.setForeground(Color.white);
    }//GEN-LAST:event_jlSalirMouseEntered

    private void jlSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseExited
        jlSalir.setForeground(new Color(178, 208, 158));
    }//GEN-LAST:event_jlSalirMouseExited

    private void jlIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlIngresarMouseEntered
        jlIngresar.setForeground(Color.white);
    }//GEN-LAST:event_jlIngresarMouseEntered

    private void jlIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlIngresarMouseExited
        jlIngresar.setForeground(new Color(178, 208, 158));
    }//GEN-LAST:event_jlIngresarMouseExited

    private void jtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuarioMouseClicked
        if (jtUsuario.getText().equals("Ingrese su nombre de Usuario y contraseña")) {
            jtUsuario.setText("");
            jtUsuario.setForeground(Color.WHITE);
        }
        if (String.valueOf(jpPass.getPassword()).isEmpty()) {
            jpPass.setText("********");
            jpPass.setForeground(new Color(178, 208, 158));
        }

    }//GEN-LAST:event_jtUsuarioMouseClicked

    private void jpPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPassMouseClicked
        if (jtUsuario.getText().isEmpty()) {
            jtUsuario.setText("Ingrese su nombre de Usuario y Contraseña");
            jtUsuario.setForeground(new Color(178, 208, 158));
        }
        if (String.valueOf(jpPass.getPassword()).equals("contraseña")) {
            jpPass.setText("");
            jpPass.setForeground(Color.WHITE);
        }


    }//GEN-LAST:event_jpPassMouseClicked

    private void jlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseClicked
        dispose();
    }//GEN-LAST:event_jlSalirMouseClicked

    private void jlIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlIngresarMouseClicked
        ingresar();
    }//GEN-LAST:event_jlIngresarMouseClicked

    private void jpPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpPassKeyTyped
      char c = evt.getKeyChar();
        if ( c == KeyEvent.VK_ENTER) {
           ingresar();
        }
    }//GEN-LAST:event_jpPassKeyTyped

    private void barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraMousePressed

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMouseDragged
       int  x= evt.getXOnScreen();
       int  y = evt.getYOnScreen();
       this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_barraMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calendario;
    private javax.swing.JPanel barra;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel dia;
    private javax.swing.JLabel diaSemana;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlIngresar;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JPasswordField jpPass;
    private javax.swing.JTextField jtUsuario;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mes;
    // End of variables declaration//GEN-END:variables
    private void initFont(){
     jlIngresar.setFont(fuenteBoton14);
     jlSalir.setFont(fuenteBoton14);
     jtUsuario.setFont(label);
     jpPass.setFont(label);
    
    }
    
    private void calendario() {
         LocalDate fecha = LocalDate.now();

        DateTimeFormatter dayFormatter = DateTimeFormatter.ofPattern("EEEE", new Locale("es"));

        String diaSemanaString = fecha.format(dayFormatter);
        String mesString = fecha.getMonth().getDisplayName(TextStyle.FULL, new Locale("es"));
        String diaString = Integer.toString(fecha.getDayOfMonth());

        diaSemana.setText(diaSemanaString);
        mes.setText(mesString);
        dia.setText(diaString);
    }
    private void ingresar(){
    String user = jtUsuario.getText();
        Usuario encontrado = usuarioData.buscarUsuario(user);
        char[] pass = jpPass.getPassword();
        String contraseña = new String(pass);
        if (encontrado != null) {
            if (encontrado.getContraseña().equals(contraseña)) {

                switch (encontrado.getTipo()) {
                    case "V": //llama a la ventana vendedor
                        MVendedor ven = new MVendedor(encontrado);
                        ven.setLocationRelativeTo(null);
                        ven.setVisible(true);
                        dispose();
                        break;
                    case "I"://llama a la ventana Inspector
                        MInspector insp = new MInspector(encontrado);
                        insp.setLocationRelativeTo(null);
                        insp.setVisible(true);
                        dispose();
                        break;
                    case "A": //llama a la ventana Admnistrador
                        MAdministrador adm = new MAdministrador(encontrado);
                        adm.setLocationRelativeTo(null);
                        adm.setVisible(true);
                        dispose();
                        break;

                    default:
                        throw new AssertionError();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
            }
        }
    }
    
    
      public static Font cargarFuentePersonalizada(String rutaFuente, float tamanio) {
        Font fuenteCargada = null;
        try {
            fuenteCargada = Font.createFont(Font.TRUETYPE_FONT, new java.io.File(rutaFuente));
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(fuenteCargada);
            fuenteCargada = fuenteCargada.deriveFont(tamanio);
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Error al cargar la fuente: " + e);
        }
        return fuenteCargada;
    }
}
