/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import AccesoADatos.ContratoData;
import AccesoADatos.PersonaData;
import Entidades.Inmueble;
import Entidades.Usuario;
import java.awt.Color;
import AccesoADatos.InmuebleData;
import Entidades.Contrato;
import java.awt.Font;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Veronica Porqueras
 */
public class MVendedor extends javax.swing.JFrame {

    public static ContratoData controlContrato = new ContratoData();
    public static PersonaData controlPer = new PersonaData();
    public static InmuebleData controlInm = new InmuebleData();
    public static Inmueble inmubleSeleccionado = null;
    public static Contrato contratoSeleccionado = null;
    public static Usuario vendedor;
    private final Color fondo = new Color(34, 65, 93);
    private final Color fondoR = new Color(145, 146, 145);
    public static Font fuenteBoton = cargarFuentePersonalizada("src/Img/font/UniversBlack.ttf", 18);
    public static Font fuenteNombre = cargarFuentePersonalizada("src/Img/font/UniversBlack.ttf", 22);
    public static Font fuenteLabel = cargarFuentePersonalizada("src/Img/font/Univers-light-normal.ttf", 22);

    
    
    public MVendedor(Usuario ven) {
        initComponents();
        initFont();
        jtNombreSombra.setBackground(new Color(34, 65, 93, 200));
        vendedor = ven;
        nombreVendedor(ven);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtNombre = new javax.swing.JLabel();
        jtNombreSombra = new javax.swing.JLabel();
        jlInmueble1 = new javax.swing.JLabel();
        jlSalir = new javax.swing.JLabel();
        jlContacto = new javax.swing.JLabel();
        jlListarInmuebles = new javax.swing.JLabel();
        jlMultas = new javax.swing.JLabel();
        jlContratos = new javax.swing.JLabel();
        jlInquilinos = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtNombre.setFont(new java.awt.Font("Univers-Black", 2, 36)); // NOI18N
        jtNombre.setForeground(new java.awt.Color(255, 255, 255));
        jtNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtNombre.setText("Nombre");
        jPanel1.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 170, 50));

        jtNombreSombra.setFont(new java.awt.Font("Univers-Black", 2, 36)); // NOI18N
        jtNombreSombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtNombreSombra.setText("Nombre");
        jPanel1.add(jtNombreSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 50));

        jlInmueble1.setBackground(new java.awt.Color(34, 65, 93));
        jlInmueble1.setFont(new java.awt.Font("Univers-Black", 1, 14)); // NOI18N
        jlInmueble1.setForeground(new java.awt.Color(255, 255, 255));
        jlInmueble1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlInmueble1.setText("CREAR INMUEBLE");
        jlInmueble1.setPreferredSize(new java.awt.Dimension(163, 30));
        jlInmueble1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlInmueble1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlInmueble1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlInmueble1MouseExited(evt);
            }
        });
        jPanel1.add(jlInmueble1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 311, 163, 30));

        jlSalir.setBackground(new java.awt.Color(34, 65, 93));
        jlSalir.setFont(new java.awt.Font("Univers-Black", 1, 18)); // NOI18N
        jlSalir.setForeground(new java.awt.Color(255, 255, 255));
        jlSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalir.setText("SALIR");
        jlSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlSalir.setPreferredSize(new java.awt.Dimension(163, 30));
        jlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlSalirMouseExited(evt);
            }
        });
        jPanel1.add(jlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 525, 163, 31));

        jlContacto.setBackground(new java.awt.Color(147, 151, 149));
        jlContacto.setFont(new java.awt.Font("Univers-Black", 0, 18)); // NOI18N
        jlContacto.setForeground(new java.awt.Color(255, 255, 255));
        jlContacto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlContacto.setText("CONTACTOS");
        jlContacto.setPreferredSize(new java.awt.Dimension(163, 30));
        jlContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlContactoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlContactoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlContactoMouseExited(evt);
            }
        });
        jPanel1.add(jlContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 217, 163, 30));

        jlListarInmuebles.setBackground(new java.awt.Color(34, 65, 93));
        jlListarInmuebles.setFont(new java.awt.Font("Univers-Black", 0, 14)); // NOI18N
        jlListarInmuebles.setForeground(new java.awt.Color(255, 255, 255));
        jlListarInmuebles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlListarInmuebles.setText("LISTAR INMUEBLES");
        jlListarInmuebles.setPreferredSize(new java.awt.Dimension(163, 30));
        jlListarInmuebles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlListarInmueblesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlListarInmueblesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlListarInmueblesMouseExited(evt);
            }
        });
        jPanel1.add(jlListarInmuebles, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 263, 163, 30));

        jlMultas.setBackground(new java.awt.Color(34, 65, 93));
        jlMultas.setFont(new java.awt.Font("Univers-Black", 1, 18)); // NOI18N
        jlMultas.setForeground(new java.awt.Color(255, 255, 255));
        jlMultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMultas.setText("MULTAS");
        jlMultas.setPreferredSize(new java.awt.Dimension(163, 30));
        jlMultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMultasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMultasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMultasMouseExited(evt);
            }
        });
        jPanel1.add(jlMultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 359, 163, 30));

        jlContratos.setBackground(new java.awt.Color(34, 65, 93));
        jlContratos.setFont(new java.awt.Font("Univers-Black", 1, 18)); // NOI18N
        jlContratos.setForeground(new java.awt.Color(255, 255, 255));
        jlContratos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlContratos.setText("CONTRATOS");
        jlContratos.setPreferredSize(new java.awt.Dimension(163, 30));
        jlContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlContratosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlContratosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlContratosMouseExited(evt);
            }
        });
        jPanel1.add(jlContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 405, 163, 30));

        jlInquilinos.setBackground(new java.awt.Color(34, 65, 93));
        jlInquilinos.setFont(new java.awt.Font("Univers-Black", 1, 18)); // NOI18N
        jlInquilinos.setForeground(new java.awt.Color(255, 255, 255));
        jlInquilinos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlInquilinos.setText("INQUILINOS");
        jlInquilinos.setPreferredSize(new java.awt.Dimension(163, 30));
        jlInquilinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlInquilinosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlInquilinosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlInquilinosMouseExited(evt);
            }
        });
        jPanel1.add(jlInquilinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 452, 163, 32));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BG_VENTA.png"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlContactoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlContactoMouseEntered
        jlContacto.setForeground(Color.BLACK);
        jlContacto.setBackground(fondo);
    }//GEN-LAST:event_jlContactoMouseEntered

    private void jlContactoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlContactoMouseExited
        jlContacto.setForeground(Color.WHITE);
        jlContacto.setBackground(fondo);
    }//GEN-LAST:event_jlContactoMouseExited

    private void jlListarInmueblesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarInmueblesMouseEntered
        jlListarInmuebles.setForeground(Color.BLACK);
        jlListarInmuebles.setBackground(fondoR);
    }//GEN-LAST:event_jlListarInmueblesMouseEntered

    private void jlMultasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMultasMouseEntered
        jlMultas.setForeground(Color.BLACK);
        jlMultas.setBackground(fondoR);
    }//GEN-LAST:event_jlMultasMouseEntered

    private void jlContratosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlContratosMouseEntered
        jlContratos.setForeground(Color.BLACK);
        jlContratos.setBackground(fondoR);
    }//GEN-LAST:event_jlContratosMouseEntered

    private void jlInquilinosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInquilinosMouseEntered
        jlInquilinos.setForeground(Color.BLACK);
        jlInquilinos.setBackground(fondoR);
    }//GEN-LAST:event_jlInquilinosMouseEntered

    private void jlSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseEntered
        jlSalir.setForeground(Color.BLACK);
        jlSalir.setBackground(fondoR);
    }//GEN-LAST:event_jlSalirMouseEntered

    private void jlListarInmueblesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarInmueblesMouseExited
        jlListarInmuebles.setForeground(Color.WHITE);
        jlListarInmuebles.setBackground(fondo);
    }//GEN-LAST:event_jlListarInmueblesMouseExited

    private void jlMultasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMultasMouseExited
        jlMultas.setForeground(Color.WHITE);
        jlMultas.setBackground(fondo);
    }//GEN-LAST:event_jlMultasMouseExited

    private void jlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseClicked
        dispose();
        Logging inicio = new Logging();
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
    }//GEN-LAST:event_jlSalirMouseClicked

    private void jlContratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlContratosMouseClicked
        ListarContratos lista = new ListarContratos(null, rootPaneCheckingEnabled);
        lista.setLocationRelativeTo(null);
        lista.setVisible(true);
    }//GEN-LAST:event_jlContratosMouseClicked

    private void jlListarInmueblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarInmueblesMouseClicked
        ListarInmuebles listaInmueble = new ListarInmuebles(this, rootPaneCheckingEnabled, vendedor);
        listaInmueble.setLocationRelativeTo(null);
        listaInmueble.setVisible(true);
    }//GEN-LAST:event_jlListarInmueblesMouseClicked

    private void jlInquilinosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInquilinosMouseClicked
        AdmPersona perso = new AdmPersona(this, rootPaneCheckingEnabled);
        perso.setLocationRelativeTo(null);
        perso.setVisible(true);
    }//GEN-LAST:event_jlInquilinosMouseClicked

    private void jlMultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMultasMouseClicked
        ListarMultas multa = new ListarMultas(this, rootPaneCheckingEnabled);
        multa.setLocationRelativeTo(null);
        multa.setVisible(true);

    }//GEN-LAST:event_jlMultasMouseClicked

    private void jlInmueble1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInmueble1MouseClicked
        AdmInmuebles inmueble = new AdmInmuebles(this, rootPaneCheckingEnabled);
        inmueble.setLocationRelativeTo(null);
        inmueble.setVisible(true);
    }//GEN-LAST:event_jlInmueble1MouseClicked

    private void jlInmueble1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInmueble1MouseEntered
        jlInmueble1.setForeground(Color.BLACK);
        jlInmueble1.setBackground(fondoR);
    }//GEN-LAST:event_jlInmueble1MouseEntered

    private void jlInmueble1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInmueble1MouseExited
        jlInmueble1.setForeground(Color.WHITE);
        jlInmueble1.setBackground(fondo);
    }//GEN-LAST:event_jlInmueble1MouseExited

    private void jlContratosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlContratosMouseExited
        jlContratos.setForeground(Color.WHITE);
        jlContratos.setBackground(fondo);
    }//GEN-LAST:event_jlContratosMouseExited

    private void jlInquilinosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInquilinosMouseExited
        jlInquilinos.setForeground(Color.WHITE);
        jlInquilinos.setBackground(fondo);
    }//GEN-LAST:event_jlInquilinosMouseExited

    private void jlSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseExited
        jlSalir.setForeground(Color.WHITE);
        jlSalir.setBackground(fondo);
    }//GEN-LAST:event_jlSalirMouseExited

    private void jlContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlContactoMouseClicked
        AdmPersona persona = new AdmPersona(null, rootPaneCheckingEnabled);
        persona.setLocationRelativeTo(null);
        persona.setVisible(true);

    }//GEN-LAST:event_jlContactoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlContacto;
    private javax.swing.JLabel jlContratos;
    private javax.swing.JLabel jlInmueble1;
    private javax.swing.JLabel jlInquilinos;
    private javax.swing.JLabel jlListarInmuebles;
    private javax.swing.JLabel jlMultas;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JLabel jtNombre;
    private javax.swing.JLabel jtNombreSombra;
    // End of variables declaration//GEN-END:variables
private void nombreVendedor(Usuario nombre) {
        jtNombreSombra.setText(nombre.getUsuario());
        jtNombre.setText(nombre.getUsuario());
    }

    private void initFont() {
        jlInmueble1.setFont(fuenteBoton);
        jlContacto.setFont(fuenteBoton);
        jlContratos.setFont(fuenteBoton);
        jlInmueble1.setFont(fuenteBoton);
        jlInquilinos.setFont(fuenteBoton);
        jlListarInmuebles.setFont(fuenteBoton);
        jlMultas.setFont(fuenteBoton);
        jlSalir.setFont(fuenteBoton);
        jtNombre.setFont(fuenteNombre);
        jtNombreSombra.setFont(fuenteNombre);
    }

    ;

public static Font cargarFuentePersonalizada(String rutaFuente, float tamanio) {
        Font fuenteCargada = null;
        try {
            fuenteCargada = Font.createFont(Font.TRUETYPE_FONT, new java.io.File(rutaFuente));
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(fuenteCargada);
            fuenteCargada = fuenteCargada.deriveFont(tamanio);
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Error al cargar la fuente: " + e);
        }
        return fuenteCargada;
    }
}
